name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-1
      S3_BUCKET_NAME: code-sprig-bucket
      EB_APP_NAME: code-sprig-v3
      EB_ENV_NAME: Code-sprig-v3-env
      ZIP_FILE: deploy-${{ github.sha }}.zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create deployment bundle
        run: |
          zip -r $ZIP_FILE . -x "*.git*" "*__pycache__*" "venv/*" "*.idea*"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp $ZIP_FILE s3://$S3_BUCKET_NAME/$ZIP_FILE

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name $EB_APP_NAME \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=$S3_BUCKET_NAME,S3Key=$ZIP_FILE

          aws elasticbeanstalk update-environment \
            --environment-name $EB_ENV_NAME \
            --version-label ${{ github.sha }}
